# Exported from Render on 2024-06-11T16:15:06Z
services:
- type: web
  name: enecad-api-3
  runtime: docker
  repo: https://github.com/ds-digital-23/enecad-api
  plan: free
  envVars:
  - key: JWT_SECRET
    sync: false
  - key: ALGORITHM
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: TEST_MODE
    sync: false
  - key: DB_URL
    sync: false
  - key: API_VERSION
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
